timezone: "Melbourne"
name: "Website name"
url: ""
app_domain: ""
cdn_url: ""
breakpoints:
  -
    name: "phone"
    query: "(max-width: 480px)"
authors:
  solnic:
    name: Piotr Solnica
    url: https://twitter.com/_solnic_
  timriley:
    name: Tim Riley
    url: https://twitter.com/timriley
  flash-gordon:
    name: Nikita Shilnikov
    url: https://twitter.com/NikitaShilnikov
