language: node_js
node_js:
  - "10.16.0"
install:
  - cd next && yarn
script:
  - cd next && node_modules/@antora/cli/bin/antora site.yml
deploy:
  local_dir: next/build/site
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  target-branch: gh-pages
  on:
    branch: master
